name: pdf4ever
description: A cyberpunk-grade PDF editor focused on inline text editing and visual accuracy.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  pdfx: ^2.3.0
  pdf: ^3.10.4
  path_provider: ^2.1.2
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  printing: ^5.11.0
  universal_html: ^2.2.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - assets/fonts/Lato.ttf    
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Anton-Regular.ttf
    - assets/fonts/Barlow-Regular.ttf
    - assets/fonts/CrimsonText-Regular.ttf
    - assets/fonts/FiraSans-Regular.ttf
    - assets/fonts/Hind-Regular.ttf
    - assets/fonts/Lato.ttf
    - assets/fonts/Lato-Regular.ttf
    - assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
    - assets/fonts/Mukta-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
    - assets/fonts/OpenSans-ExtraBold.ttf
    - assets/fonts/OpenSans-ExtraBoldItalic.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-Light.ttf
    - assets/fonts/OpenSans-LightItalic.ttf
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Semibold.ttf
    - assets/fonts/OpenSans-SemiboldItalic.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Questrial-Regular.ttf
    - assets/fonts/Roboto-Black.ttf
    - assets/fonts/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - assets/fonts/RobotoCondensed-Bold.ttf
    - assets/fonts/RobotoCondensed-BoldItalic.ttf
    - assets/fonts/RobotoCondensed-Italic.ttf
    - assets/fonts/RobotoCondensed-Light.ttf
    - assets/fonts/RobotoCondensed-LightItalic.ttf
    - assets/fonts/RobotoCondensed-Regular.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-Light.ttf
    - assets/fonts/Roboto-LightItalic.ttf
    - assets/fonts/Roboto-Medium.ttf
    - assets/fonts/Roboto-MediumItalic.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Thin.ttf
    - assets/fonts/Roboto-ThinItalic.ttf
    - assets/fonts/SpaceMono-Regular.ttf
    - assets/fonts/TitilliumWeb-Regular.ttf
    - assets/fonts/WorkSans[wght].ttf
    - assets/fonts/WorkSans-Italic[wght].ttf
    - assets/fonts/Didot.ttf
    