name: pdf4ever
description: A cyberpunk-grade PDF editor focused on inline text editing and visual accuracy.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  pdfx: ^2.3.0
  pdf: ^3.10.4
  path_provider: ^2.1.2
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  printing: ^5.11.0
  universal_html: ^2.2.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - assets/fonts/Arial.ttf
    - assets/fonts/ArialBlack.ttf
    - assets/fonts/Verdana.ttf
    - assets/fonts/Tahoma.ttf
    - assets/fonts/TrebuchetMS.ttf
    - assets/fonts/TimesNewRoman.ttf
    - assets/fonts/Georgia.ttf
    - assets/fonts/PalatinoLinotype.ttf
    - assets/fonts/Garamond.ttf
    - assets/fonts/CourierNew.ttf
    - assets/fonts/LucidaConsole.ttf
    - assets/fonts/LucidaSansUnicode.ttf
    - assets/fonts/Impact.ttf
    - assets/fonts/ComicSansMS.ttf
    - assets/fonts/Calibri.ttf
    - assets/fonts/Cambria.ttf
    - assets/fonts/Candara.ttf
    - assets/fonts/Constantia.ttf
    - assets/fonts/Corbel.ttf
    - assets/fonts/SegoeUI.ttf
    - assets/fonts/Helvetica.ttf
    - assets/fonts/HelveticaNeue.ttf
    - assets/fonts/GillSans.ttf
    - assets/fonts/Futura.ttf
    - assets/fonts/FranklinGothicMedium.ttf
    - assets/fonts/CenturyGothic.ttf
    - assets/fonts/BookAntiqua.ttf
    - assets/fonts/Baskerville.ttf
    - assets/fonts/Rockwell.ttf
    - assets/fonts/BodoniMT.ttf
    - assets/fonts/Avenir.ttf
    - assets/fonts/Optima.ttf
    - assets/fonts/Didot.ttf
    - assets/fonts/Univers.ttf
    - assets/fonts/MyriadPro.ttf
    - assets/fonts/MinionPro.ttf
    - assets/fonts/NeueHaasGrotesk.ttf
    - assets/fonts/ProximaNova.ttf
    - assets/fonts/Lato.ttf
    - assets/fonts/Roboto-Regular.ttf

